#!/bin/bash

 ##############################################################################
 #                                                                            #
 # Copyright 2022 MachineWare GmbH                                            #
 # All Rights Reserved                                                        #
 #                                                                            #
 # This is unpublished proprietary work owned by MachineWare GmbH. It may be  #
 # used, modified and distributed in accordance to the license specified by   #
 # the license file in the root directory of this project.                    #
 #                                                                            #
 ##############################################################################

home="$(cd $(dirname $(dirname ${BASH_SOURCE[0]} )) &>/dev/null && pwd)"
formatter="$home/cmake/Tools/$(uname -s)/clang-format-15.$(arch)"
srcdirs="$home/src $home/include $home/test"
sources=$(find $srcdirs -name '*.h' -or -name '*.cpp' | grep -v googletest)
exec $formatter --Werror $sources $@
