name: coverage

on:
  push:
    branches:
      - 'main'
      - 'dev**'
  pull_request:
    branches:
      - 'main'

env:
  BUILD_TYPE: DEBUG
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}

jobs:
  coverage:
    name: coverage
    runs-on: self-hosted-ubuntu-22.04

    steps:
      - name: Checkout Model
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{secrets.CI_TOKEN}}

      - name: Configure Models
        run: cmake -B BUILD -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVCML_SILKIT_TESTS=ON -DVCML_SILKIT_COVERAGE=ON .

      - name: Build Models
        run: cmake --build BUILD --config ${{env.BUILD_TYPE}} -j $(nproc)

      - name: Test Models
        working-directory: ${{github.workspace}}/BUILD
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Generate Coverage Report
        run: |
          mkdir -p vcml-silkit-coverage-report
          gcovr --html-details -f 'include/*' -f 'src/*' --output vcml-silkit-coverage-report/vcml-silkit.html --exclude-lines-by-pattern '\s*(VCML|MWR)_ERROR.*'

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: vcml-silkit-coverage-report
          path: vcml-silkit-coverage-report/
